spring:
  application:
    name: calorie-tracker-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/calorie_tracker
    username: akashsingh
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6380

server:
  port: ${PORT:8081}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expirationMs: 86400000 # 24 hours

google:
  clientId: ${GOOGLE_CLIENT_ID:101851020637-3pifturaj43ied5tv3hlld6mv13s6lte.apps.googleusercontent.com}

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: calorie-tracker-bucket

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

nutrition:
  api:
    url: https://trackapi.nutritionix.com/v2/natural/nutrients
    appId: ${NUTRITIONIX_APP_ID:}
    appKey: ${NUTRITIONIX_APP_KEY:}

logging:
  level:
    root: INFO
    com.calorie.tracker: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
